### ISSUE TITLE
Mod doesn't work in multiplayer

### ISSUE THREAD

**Issue by ghost** [danny50610/ImmortalObjectTip#2]
Mod doesn't work in multilayer

**Comment by danny50610** [comment]
Hello

Can you tell more Information?

Which mod version do you use?
Which function can not be used?

(Sorry, my English isn't very good)

**Comment by ghost** [comment]
None of the pop-up messages are displayed. I tried to hit invincible players, NPC and bedrock. I use this one: ImmortalObjectTip-1.11.2-0.3.23

**Comment by danny50610** [comment]
It works fine when I test by myself.
I think I need more information,

- Does it happen in singleplayer? Or just in multiplayer?
- Are there any mods installed? Please show your mod list with version.
- Do you use Optifine? Which version?
- Which version of Forge do you use?

**Comment by ghost** [comment]
It happens exactly in multiplayer.
List of my mods: 
  AmbientSounds v1.2.2 mc1.11
  BetterPvP_1.12.6_Forge_1.11
  easiervillagertrading-1.1.0
  Fix MC-2518
  ImmortalObjectTip-1.11.2-0.3.23
  MineMenu-1.11.2-1.5.0-universal
  OptiFine_1.11.2_HD_U_B7
  XRay-48
I use forge1.11.2-13.20.0.2282 version of Forge.

**Comment by danny50610** [comment]
I think some mod cause problem. Try remove one by one to test.
